---
title: "Homework 8"
author: "Ameth FAYE"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("C:/Users/HP/Desktop/ISEP2CoursR2024/Homework 7.R")



### Answers to HomeWork 8

#' calculer la quantite achete en kg; 
#' calculer le prix unitaire ;
#' Calculer les depenses de consommations ; 
#' Valeurs aberrantes :: corrections ; 


###1) Calculons la quantité achetée
## Poids 
library(data.table)
fusion <- data.table(fusion)
setnames(fusion,"poids","poids_cons")

# Vérification des NA dans poids 
anyNA(fusion$poids_cons)
sum(is.na(fusion$poids_cons))

# (Pas de NA dans poids_cons)

## Quantity conso en unite standard (kg)
fusion [,poids_cons:=as.numeric(poids_cons)]
fusion [, Qtty_achetee_kg:= poids_cons*Qtty_achat/1000]

unique(fusion$Qtty_achetee_kg)

###2) calculons le prix unitaire(en kg)

unique(fusion$Value_achat)
fusion [, prix_unitaire:= Value_achat/Qtty_achetee_kg]
unique(fusion$prix_unitaire)

###3) Calculons les depenses de consommations

## Quantity conso en unite standard (kg)
fusion [, Qtty_cons_kg:= poids_cons*Qtty_cons/1000]

fusion [, depenses_cons:= Qtty_cons*prix_unitaire]

###4) Valeurs aberrantes et corrections
cereales_anormal <- fusion[Qtty_cons_kg>1000]


library(dplyr)
# Calculer la médiane de la variable qtty_cons_kg
median_value <- median(fusion$Qtty_cons_kg, na.rm = TRUE)
# Remplacer les valeurs aberrantes par la médiane
fusion$qtty_cons_kg[which(fusion$Qtty_cons_kg > 1000)] <- median_value

unique(fusion$Qtty_cons)
```

